# Generated by Django 3.1.2 on 2021-08-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
